### ISSUE TITLE
Yaoi Fanclube

### ISSUE THREAD

**Issue by KaraSupergirl** [keiyoushi/tachiyomi-extensions-source#1217]
### Source name

Yaoi Fanclube 2

### Source link

https://www.yaoifanclub.com/

### Source language

Portuguese 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Norsze** [comment]
Source name is **Yaoi Fan Club** or **Yaoi Fan Clube** (with or without spaces) not _Yaoi Fanclube 2_ according to their website

**Comment by tiauva** [comment]
There is no reason to put our website on something like this. Since it is an open site, it has no advertisements. and in addition we also post our works on mangadex.
Furthermore, the last time I talked to a guy, he gave me his word that he would no longer put my site on the extension since we posted it on mangadex.
So please. Leave it as it is. Our website follows internet guidelines. There are no advertisements, it is free to the public, free of charge, I do not require any means of payment or anything.
thanks in advance
