### ISSUE TITLE
MangaDex - No chapters found if the manga has multiple versions

### ISSUE THREAD

**Issue by LunarEclipse363** [keiyoushi/tachiyomi-extensions-source#1709]
### Source information

MangaDex Multi 1.4.192

### Source language

English

### Steps to reproduce

1. Search for a manga that has multiple versions, example: "Her Pet"
2. Try to add it to the library
3. Get a "no chapters found" message

### Expected behavior

One of:
- Getting an option to choose which version to use when adding to library
- Splitting the multiple versions in search
- At least going with the latest available version to do something instead of nothing as a quick fix

### Actual behavior

No chapters found

### Mihon/Tachiyomi version

0.16.4

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
If it gives you a "No Chapters Found" message, that's because no chapters were found for the selected language.

Some manga may list a certain language in the source page/WebView, but for MangaDex, some of those chapters (say for example it says MangaPlus) aren't actually on MangaDex. They are just redirects to wherever it's actually hosted at.

If you're looking for "Her Pet", it shows there's Russian chapters available in WebView, which if you want those to appear (or any other language that doesn't fall into the redirect bit above), you will need to enable the language in both the Extension & the Source tab. Then you can search in that language for that extension.
