### ISSUE TITLE
Hentaivn Change URL

### ISSUE THREAD

**Issue by MakatoKishei** [keiyoushi/tachiyomi-extensions-source#2215]
### Source information

Hentaivn 1.4.31

### Source language

Vietnamese 

### Source new URL

https://hentaivn.bid/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Consider using the option in the extension's setting (Browse Page > Extensions tab > HentaiVN settings) to change the domain/URL for now

If you have any confirmation/details about the original site being dead, consider adding that info in this issue request, otherwise if it's a temporary site/URL change, maybe close the issue once the original site is back online

**Comment by vetleledaal** [comment]
The domain redirects to https://henvn.tv, not https://hentaivn.bid
