### ISSUE TITLE
Manhuaplus.org not working

### ISSUE THREAD

**Issue by bijita1** [keiyoushi/tachiyomi-extensions-source#2613]
### Source information

Manhuaplus.org

### Source language

English

### Steps to reproduce

Don't download

### Expected behavior

The download should happen

### Actual behavior

File downloading

### Mihon/Tachiyomi version

0.16.3

### Android version

Lineageos 21 (Android 14)

### Other details

I'm using a raspberry pi 4B

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by bijita1** [comment]
Sorry on my errors in t
How to produce the bug simply download the first chapter of any manhua it will say the number of page but not downloading anything

**Comment by mohamedotaku** [comment]
the issue is not from extension. 
chek your network or your firewall, if you use an adblock in raspberry pi chek if it block download.

![Screenshot_20240427-230258](https://github.com/keiyoushi/extensions-source/assets/25872771/e218a0c7-b311-4b27-89ce-6b180180a7d0)
![Screenshot_20240427-230323](https://github.com/keiyoushi/extensions-source/assets/25872771/28871741-9f6c-40c2-9011-4cdadac40ba5)

**Comment by AwkwardPeak7** [comment]
cannot reproduce
