### ISSUE TITLE
https://www.zinmangaa.us/

### ISSUE THREAD

**Issue by Achuabdu** [keiyoushi/tachiyomi-extensions-source#2924]
### Source name

Zinmangaa

### Source link

https://www.zinmangaa.us/

### Source language

English

### Other details

![Screenshot_2024-05-10-10-21-24-842_com opera browser afin](https://github.com/keiyoushi/extensions-source/assets/145904014/c624c5ef-edd0-4888-97d8-e4b69c1a3e0e)

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
From a quick glance at the sources in #2920, #2922, and #2923, it seems like they're the same style/theme.

Maybe consider putting all the links together of zinmanga, if you find any more, instead of creating separate issues. Then they could be mirror URLs if they are the same style & have the same content.

**Comment by vetleledaal** [comment]
Chapters don't work at all. Open another issue if they fix it.
