### ISSUE TITLE
Pununi

### ISSUE THREAD

**Issue by Jhondeivis12** [keiyoushi/tachiyomi-extensions-source#3289]
### Source name

Pununi Scan

### Source link

https://punuprojects.com

### Source language

Spanish

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
Uses HeanCMS theme but not has content yet

**Comment by bapeey** [comment]
Site is down 
![image](https://github.com/keiyoushi/extensions-source/assets/90949336/7d71949f-6556-4b03-a037-ffe0b34623da)

TR: Due to internal issues, we have decided to stop having a website (it's quite expensive), so for the time being, we will only be uploading the series to TMO. We hope you support us with this decision
