### ISSUE TITLE
Reading any chapter from ReadComicOnline gives the error java.lang.Exception: Solve captcha in WebView

### ISSUE THREAD

**Issue by moosyu** [keiyoushi/tachiyomi-extensions-source#4733]
### Source information

ReadComicOnline

### Source language

English

### Steps to reproduce

1. Tap on a chapter from ReadComicOnline
2. Get error to solve captcha in webview

### Expected behavior

The chapter opens

### Actual behavior

java.lang.Exception: Solve captcha in WebView

### Mihon/Tachiyomi version

0.16.5

### Android version

Android 9

### Other details

![image](https://github.com/user-attachments/assets/a844f8c9-85f0-4a07-81bb-820ed399af6f)
The captchas look like that and they show up every chapter. On mobile trying to get to this point through WebView leads to the error:
net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Duplicate of #4115

Doesn't matter if you solve the captcha (set the extension to use Server 2 in the extension settings), you can't load the chapter images afterwards, since the source itself was actively breaking the extension after each fix. You should find/migrate to a better source & not give them the ad revenue.

Also that ERR_HTTP_RESPONSE_CODE_FAILURE page you're seeing is a spam/ad link the site tries to redirect you to.

**Comment by moosyu** [comment]
whoops sorry for wasting your time, idk how i missed that. ty.
