### ISSUE TITLE
Galaxy manga AR Version 

### ISSUE THREAD

**Issue by SLYVERRR** [keiyoushi/tachiyomi-extensions-source#4745]
### Source information

Galaxy manga AR

### Source language

arabic

### Source new URL

https://galaxymanga.net

### Other details

The link of the AR version has changed 

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SLYVERRR** [comment]
The link ok the extension has changed updste it pls

**Comment by Smol-Ame** [comment]
The extension has been replaced with an updated version, read what the bot says. You should search the existing issues (both open & closed) before opening a new issue, and acknowledging that you did when you didn't. Also consider joining the Keiyoushi Discord server, and check the status-update, where this fix has been in place since July.

![image](https://github.com/user-attachments/assets/144570f5-a38e-46ff-9284-962e11a5c178)
