### ISSUE TITLE
Asuratoon changed to asuracomics

### ISSUE THREAD

**Issue by ffuentesm** [keiyoushi/tachiyomi-extensions-source#5070]
### Source information

Asura Scans 1.4.58

### Source language

English

### Source new URL

Asuracomics.net

### Other details

The website chnages and the extension cant detect the mangas anymore.
![Screenshot_20240915_014333_Tachiyomi](https://github.com/user-attachments/assets/7fe2c916-8c6e-4e37-99cf-8982961f500d)

As you can see, when I click on the web view, the page is redirected.

![Screenshot_20240915_013939_Tachiyomi](https://github.com/user-attachments/assets/c378fb8b-e927-4710-95da-c0543c343b23)
![Screenshot_20240915_014045_Tachiyomi](https://github.com/user-attachments/assets/74d1525a-088c-4352-97c2-493f85c2f9e4)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
1) You're not using our Asura Scans extension, the Keiyoushi version is 1.4.39. Uninstall your extension, reinstall our repo's version of it, and migrate all your entries back into Asura Scans afterwards. If you have questions/issues, come to the Keiyoushi Discord repo-support channel for help.
2) The Keiyoushi version already uses the asuracomic.net, and since you miswrote the URL so the auto-mod didn't automatically flag it as a duplicate/already exists
