### ISSUE TITLE
Comick

### ISSUE THREAD

**Issue by TeoXP** [keiyoushi/tachiyomi-extensions-source#5142]
### Source information

Comick

### Source language

English

### Steps to reproduce

1.Use any app that can use the repo
2 Install comick extension
3 Try to read a chapter

### Expected behavior

Show the chapter

### Actual behavior

Unable to rezolve host api.comick.com no address

### Mihon/Tachiyomi version

Mihon 0.16.5

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems to be working fine, I think it's an internet-related issue on your end (if you are unable to browse/see any titles/chapters on Comick):
* Check router/ad-block/VPN settings to see if Comick is being blocked (and whitelist it)
* Try switching networks (mobile data to WiFi)
* Try using a VPN
* If you have DNS over HTTPS enabled in your Mihon Settings > Advanced page, maybe change/turn it off (and restart the app after changing it) to see if that helps


Otherwise, I believe there's a limitation of their API where new chapters released 3-4 hours ago aren't available on their API yet, so you just have to wait past 4 hours of release to read them.

**Comment by vetleledaal** [comment]
By the error message this sounds like an issue with your DNS provider. Toggling DoH in the settings will usually resolve this, otherwise you need to use a VPN.

As it's not an problem with the extension I'll be closing this issue. If you need additional support please join the #support channel on Discord.
