### ISSUE TITLE
dark pages and covers

### ISSUE THREAD

**Issue by Nerannnn** [keiyoushi/tachiyomi-extensions-source#5159]
### Source information

Bakai 1.4.4

### Source language

Portuguese 

### Steps to reproduce

When I open the extension everything is apparently normal, but the covers of some works do not load and when I open any manga, after a long wait, the screen goes black

### Expected behavior

the manga covers appear and the chapter reading is possible

### Actual behavior

The covers of some manga do not appear, in the case of the most recent releases, and the chapters have a black screen after a long wait.

### Mihon/Tachiyomi version

0.15.3

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
This issue was brought up yesterday in the Keiyoushi Discord repo-support channel, but after some troubleshooting, it seemed like it fixed itself for the user that was having this issue. It could've just been a source's server/website-related issue, but hard to say. It was working fine when I was checking it last night. Can you check WebView to see if the covers/chapters themselves exist on their site?

Unfortunately, they are geo-blocking some parts of the world, which means I've got to cycle my VPN till it connects to somewhere where it isn't blocked to see if it's a personal issue, site issue, or extension-related issue.

**After-edit** (connected to Netherlands server): Seems to be loading up fine on my end, covers & chapters, could you name an entry/chapter that you are having an issue with (don't show/screenshot any content to avoid NSFW in public channel/post)?

**Comment by Nerannnn** [comment]
Initially I thought the problem was only with recent releases but it seems that with any manga I open, the page loads and loads and then the screen goes black, in fact I already checked on webview and everything is normal with the source site

**Comment by Nerannnn** [comment]
when I open the extension it looks like this
![Screenshot_20240924-143232](https://github.com/user-attachments/assets/3c30d2ca-0025-47cb-8492-004ef4b06142)
and when I open a chapter it looks like this
![Screenshot_20240924-143311](https://github.com/user-attachments/assets/71f8898c-01df-4f25-add1-59fc66d4dea8)
