### ISSUE TITLE
Issue with Manga-scantrad

### ISSUE THREAD

**Issue by iscarter** [keiyoushi/tachiyomi-extensions-source#5206]
### Source information

Magan-scan 1.4.35

### Source language

"French"

### Steps to reproduce

1. Open the extension to see the List of his manga 
2. enter a manga 
3. click on a chapter 
4. the image is not displayed

![Screenshot_20240924_213404_Aniyomi](https://github.com/user-attachments/assets/d9576406-da48-4577-9ee2-1f39fb1e0eab)

### Expected behavior

When I click on a chapter, the images must be displayed so that I can read them.
Can you please solve the problem with Cloudflare? Each time we are oblique to open the web view.
It would be nice if we could fix the problem with Cloudflare so that we could go permanently.
Thank you.

### Actual behavior

No image is displayed when we open a chapter.

### Mihon/Tachiyomi version

Aniyomi 0.16.4.3

### Android version

Android 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Extension seems to be working fine after passing Cloudflare.

For this issue of "The image couldn't be loaded", check WebView or in your own browser to see if said pages exist on the source's website. If they do exist, go to Mihon Settings > Data and storage, and "Clear chapter cache", then try opening it again after passing Cloudflare. If that doesn't help, come to the Keiyoushi Discord repo-support channel for more help.

As for the Cloudflare "issue", that's the source's way of protecting itself from bots/attacks/spam. Cloudflare and/or the source can change what they block whenever they want, understand when it happens & know how to change the user-agent when that happens (by following the [Keiyoushi Troubleshooting Guide](https://keiyoushi.github.io/docs/guides/troubleshooting#cloudflare)). There's really nothing to fix since you/the user can pass Cloudflare & view the pages with no issue. And, passing Cloudflare doesn't mean it'll last indefinitely, some sources are more strict with the protection level they set (where you need to pass Cloudflare on every page, not just initially).

**Comment by iscarter** [comment]
Thanks for your reply. Have a great day.

**Comment by KirinRaikage** [comment]
As a French contributor, I confirm that the extension is working fine. You can close the issue if you've solved it, but you should have no issues finding a user agent that works for that specific source.

**Comment by iscarter** [comment]
Okay thanks
