### ISSUE TITLE
mgkomik: isu load image

### ISSUE THREAD

**Issue by mozzaru** [keiyoushi/tachiyomi-extensions-source#5289]
### Source information

mgkomik 1.4.50

### Source language

Id

### Steps to reproduce

Slow image loading,stable internet connection 

### Expected behavior

Some old comics stored in libraries contain pictures, very old.

### Actual behavior

.

### Mihon/Tachiyomi version

yokai last

### Android version

android 11

### Other details

![Screenshot_2024-09-28-17-40-43-12_21015a41200050f19d2d2db913bd7dc1](https://github.com/user-attachments/assets/abbe1df7-6aec-4c22-91d1-8cd38284a9cb)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
You should actually take the time to fill in the details, like version number, not even sure what you wrote in Expected behavior, yeah comics have pictures?

I would say it loads in fine, the extension does have a rate-limit but those are usually put in place so the source doesn't completely block/rate-limit you from reading. Download the chapter before reading, or better yet maybe utilize the app's features of "Download ahead" paired with "Remove after read" in Yokai Menu > Settings > Downloads. That way you'll have simple download management of downloading the next chapters as you read, and it'll delete said chapters after reading them.

**Comment by mozzaru** [comment]
I read online 

https://github.com/user-attachments/assets/cec09f55-a865-410e-bd88-703803c2a3c3

I tried the same extension, other comics are fast, but some comics are slow to load images
Thanks
