### ISSUE TITLE
reset scans domain changed again 

### ISSUE THREAD

**Issue by Rasun0** [keiyoushi/tachiyomi-extensions-source#5340]
### Source information

reset scans 1.4.41

### Source language

English 

### Source new URL

https://reset-scans.xyz/

### Other details

they have a temporary one before which was https://rspro.xyz/ this is the new one https://reset-scans.xyz/
![Screenshot_20241003_095651](https://github.com/user-attachments/assets/3de44187-c513-4ac1-b023-bc678d731772)

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by bapeey** [comment]
New site uses FuzzyDoodle theme

**Comment by adalricgaming** [comment]
They changed the way the main site handles the manga. All manga have a new url that starts with https://rspro.xyz/home/manga/ instead of https://rspro.xyz/manga/

**Comment by Smol-Ame** [comment]
@adalricgaming this issue/request is for their beta site, the one listed above your comment is the issue request for the new home URL of the existing site

**Comment by Salinda001** [comment]
The url https://reset-scans.xyz/ is a beta design. Some of the manga haven't been updated since September and some don't have chapters. Currently this site https://rspro.xyz/ have all the manga/chapters and have the latest update. So I think its better have https://rspro.xyz/ url for now until they comfirms https://reset-scans.xyz/ as their official website.
