### ISSUE TITLE
XOXO Comics won't load the comics' pages

### ISSUE THREAD

**Issue by GitJakeTheJake** [keiyoushi/tachiyomi-extensions-source#5368]
### Source information

1.4.10

### Source language

English

### Source new URL

https://xoxocomic.com/

### Other details

The site is still up but the comics pages won't load. When I open a page in webview I get a "page not found" error, so the URLs/links for the comics have changed. If I enter their website on a browser and search for the comic, I can read it normally.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by GitJakeTheJake** [comment]
There is an issue and the comics won't load. The pages point to broken links.

**Comment by AwkwardPeak7** [comment]
open a "bug report" instead of "domain change"

**Comment by Smol-Ame** [comment]
Before that, check WebView for errors with said chapters. From a quick test, seems like it's fine with the few I tried. Maybe internet-related issue or the source is missing the chapters/having issues themselves. If you do make a new issue request, list the problematic entries & chapters, otherwise, come to the Keiyoushi Discord repo-support channel if you have other questions/issues.

**Comment by GitJakeTheJake** [comment]
It was a cache issue, I apologize. It is fixed. Thanks guys!
