### ISSUE TITLE
manga rock team error 1005 IP blocked

### ISSUE THREAD

**Issue by xX1bigfishXx** [keiyoushi/tachiyomi-extensions-source#5474]
### Source information

en.mangarockteam 1.4.37

### Source language

English

### Steps to reproduce

open any manga in webview
CloudFlare error 1005

### Expected behavior

open manga in web view

### Actual behavior

CloudFlare error 1005 landing page

### Mihon/Tachiyomi version

TachiyomiSY 1.10.5

### Android version

Android 11

### Other details

I am using no VPN service
![Screenshot_20241011-052658](https://github.com/user-attachments/assets/f778bb9c-ac96-44ce-9ba9-6ed0c69acb6c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
Seems like a site issue (despite the error message), check in your own browser later on.

If their page works in your own browser, but the extension isn't working, then make a new issue request. If the error is correct, and you have been IP banned, nothing we can do about it since it's a personal internet-related issue (like you don't ask the landlord to let you into the local Walmart if you were banned from the store, **fixed analogy).

Closing as a site/personal internet-related issue.

![Screenshot_20241011_023140_Firefox Nightly](https://github.com/user-attachments/assets/4d17cb16-4c1b-486d-8373-aaf815004b4d)
