### ISSUE TITLE
Modification adresse web

### ISSUE THREAD

**Issue by Obm16** [keiyoushi/tachiyomi-extensions-source#5737]
### Source information

Reaper Scans 1.4.36

### Source language

Français

### Source new URL

https://reaper-scans.fr/

### Other details

Le lien a été modifié passant de https://reaperscans.fr/
à https://reaper-scans.fr/
Raison pour laquelle les mises à jour dans l'application ne fonctionnent pas.
✓Capture du résultat dans l'application : 
![Screenshot_20241028-085709](https://github.com/user-attachments/assets/569d5328-d772-4cdf-8454-b38f06b72926)
✓Capture de l'ancien URL
![Screenshot_20241028-085723](https://github.com/user-attachments/assets/427b8db0-b857-413d-abec-7cda8f7ecd3b)
✓Capture du nouveau URL
![Screenshot_20241028-085726](https://github.com/user-attachments/assets/28ef729a-65e3-47be-bc66-748cd509ca76)

Veuillez bien examiner la requête avant de la rejeter. Merci.

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment]
The auto-moderator is closing your request because the current extension is already set to the "reaper-scans.fr" site.

Also, if your extension's version number is correct, you're not using our/Keiyoushi's version of the extension. Our Reaper Scans (FR) extension's version number is 1.4.12
* Uninstall your extension
* Check that you are using the Keiyoushi repo
* Reinstall the extension

If you have any questions or issues about this, or just for basic troubleshooting, come to the Keiyoushi Discord repo-support channel for help

**Comment by Obm16** [comment]
Le bot fais une erreur. Qu'un membre de l'équipe vérifie en personne mon signalement car il n'y a aucune mise a jour pour l'extension avec le nouveau lien.
 J'avais fais la requête hier et c'était la même réponse j'ai vérifié et toujours aucune mise à jour de l'extension. J'espère que vous prendrez vos dispositions pour satisfaire ma demande.
