### ISSUE TITLE
reset scans updates on two domains

### ISSUE THREAD

**Issue by Smognoggler** [keiyoushi/tachiyomi-extensions-source#5890]
### Source name

Reset Scans

### Source link

https://rspro.xyz/

### Source language

English

### Other details

Reset scans is updating different series on two different domains, one is https://reset-scans.xyz/ and another is https://rspro.xyz/. Current extension pulls from https://reset-scans.xyz/ which is only updating one series
suggest having two extensions 

### Acknowledgements

- [X] I have checked that the extension does not already exist by searching the [extension listing](https://keiyoushi.github.io/extensions/) and verified it does not appear there.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by kavillock** [comment]
https://reset-scans.xyz/ does not have any for now

**Comment by morethanhater** [comment]
> https://reset-scans.xyz/ does not have any for now

On the contrary, it has a working extension for it
Rspro is the one without extension

**Comment by snorlaxthepokemon** [comment]
![Screenshot_2024_1119_114614](https://github.com/user-attachments/assets/267b32cf-f95c-46f0-83fa-974e37cc8837)
![Screenshot_2024_1119_114745](https://github.com/user-attachments/assets/ff879afb-2276-4675-9122-e8610bb8138b)
Screenshots from Owner of Reset scans from their discord server.

Basically the current website on the extension takes to their backup website instead of their actual latest upload one , request to change it

**Comment by dngonz** [comment]
I avoid paid chapters, but if someone has some trouble with that please create an issue and I will try to solve it.
