### ISSUE TITLE
flame comic back 

### ISSUE THREAD

**Issue by Rasun0** [keiyoushi/tachiyomi-extensions-source#6230]
### Source information

flame comic 1.4.34

### Source language

English 

### Steps to reproduce

flame comic is back as per their recent announcement 
![Screenshot_20241123_090551](https://github.com/user-attachments/assets/90b1c8ed-d86e-4fcb-a70e-166d546b48bd)
but extension is still down despite the website is on
![Screenshot_20241123_090355](https://github.com/user-attachments/assets/46440078-4bf3-490e-aebb-86f382a995b2)
so hope you can fix the extension error soon .

### Expected behavior

extention showing an 404 error while website is up 
![Screenshot_20241123_093358](https://github.com/user-attachments/assets/c3d711b0-e69b-41db-a0e0-fa1590a3617d)

### Actual behavior

it should be up with both extensions and webview too but it's down on extension .

### Mihon/Tachiyomi version

0.17.0

### Android version

Android 14

### Other details

![Screenshot_20241123_090551](https://github.com/user-attachments/assets/fb61bcea-09be-43e1-aaa6-033a19505aac)
![Screenshot_20241123_090551](https://github.com/user-attachments/assets/069e891c-4b83-4619-9d09-ad2b5123ba35)
![Screenshot_20241123_093358](https://github.com/user-attachments/assets/fea88098-11e1-45ea-96d9-de24a881c17c)

Hope it get fix soon .

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by nobile01** [comment]
The way they have their file system changed, for instance one series used to be on this link:
https://flamecomics.xyz/series/the-novels-extra-remake
But now it's actually on this link:
https://flamecomics.xyz/series/83

Probably that's why we're getting 404? Hopefully there's a way to deal with that

**Comment by vetleledaal** [comment]
@nobile01 appreciate the additional context. The change in URL structure unfortunately means that users will have to migrate all their library entries in the next extension update.

The 404 error is just a symptom of a bigger issue. There are large structural changes to the site, so the extension has to basically be recreated from scratch. This is obviously a lot of work, and since contributors are free to work on any issue they deem important there is no time-frame for when a fix is available.

Given the popularity of the extension there _might_ be contributors that are especially invested in fixing the extension, but again, I would not count on it.

**Comment by lord-ne** [comment]
Further details, the search also currently returns 404, so users cannot migrate. As stated above, the extension is not usable until rewritten. There is already a PR open working on fixing it
