### ISSUE TITLE
Slime Read (PT-BR SOURCE)  Could not find API URL 

### ISSUE THREAD

**Issue by AnonymousPtBr** [keiyoushi/tachiyomi-extensions-source#6242]
### Source information

SlimeRead 1.4.14

### Source language

Portuguese Brazilian 

### Steps to reproduce

Don't show content.

![Screenshot_2024-11-23-20-26-02-829_app mihon debug](https://github.com/user-attachments/assets/63769df3-4f64-4ab3-a8c1-e4e08c207cf9)

### Expected behavior

Show content.

### Actual behavior

Don't show content.

### Mihon/Tachiyomi version

App version: 0.17.0-7001

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by allyaihara** [comment]
Aaaaa e agora??

**Comment by Klaus07b** [comment]
Alguém sabe como resolver?

**Comment by ddellzin** [comment]
Is there a date to fix it?

**Comment by Norsze** [comment]
NO!

Please note that creating an issue does not mean that the source will be added or fixed in a timely fashion, because the work is volunteer-based. Some sources may also be impossible to do or prohibitively difficult to maintain.

If you would like to see a request fulfilled and have the necessary skills to do so, consider contributing! Issues are up-for-grabs for any developer if there is no assigned user already.

Now can you guys wait patiently and read existing issues?
