### ISSUE TITLE
Mangatoon chapters aren't loading

### ISSUE THREAD

**Issue by Aura-13** [keiyoushi/tachiyomi-extensions-source#6256]
### Source information

Mangatoon

### Source language

English 

### Steps to reproduce

1. Select source 'mangatoon'.
2. Open a comic

### Expected behavior

All chapters of the manga should have loaded.

### Actual behavior

Only the first few and last chapters are loaded
![Screenshot_2024_1124_143925](https://github.com/user-attachments/assets/863e21d6-7a45-4821-9e1b-16cb542bb487)

### Mihon/Tachiyomi version

 0.17.0 

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### 

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/keiyoushi/extensions-source/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by vetleledaal** [comment]
The hidden chapters are not free to read. Try signing in into WebView, if that does not work you should create a feature request for reading paid chapters.

**Comment by Aura-13** [comment]
Well, taking example of the screenshot I've shared (school hunk is a girl). The free chapters are much more than 6. 

It shows only 9 chapters for EVERY series (first 6 and last 3). Just a couple of months back, it showed the entire chapter list just fine.. 

I've tried logging in to see if the issue is cleared, but it still remains same. Unfortunately, I haven't bought any paid chapters so, I can't check that.

**Comment by vetleledaal** [comment]
Currently it shows chapter 1-9 in the extension. Since the extension is not using the same interface as the official app it is limited to what you can see from a regular browser. From WebView you can see chapter 10 and onwards are not viewable (see screenshot below).

I suspect the changing amount of visible chapters is due to various promotions or events going around.

After logging into the WebView make sure you refresh the chapter list and compare with what you have access to in the WebView. They should be the same. If additional chapters do show up, some sort of login prompt could be added to the extension. If they still don't work after logging in, the extension would need to be changed so it acts like the official app, if possible. Either way, this would be a feature request. Please open one or the other after investigating.
 
![image](https://github.com/user-attachments/assets/b74a79d0-79d4-437b-a739-afa11a2406fd)
