### ISSUE TITLE
Cambio de URL de Olympus Scanlation

### ISSUE THREAD

**Issue by Athrun0311** [keiyoushi/tachiyomi-extensions-source#6300]
### Source information

Olympus Scanlation 1.4.10

### Source language

Spanish 

### Source new URL

https://olympuscomic.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL has not changed yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### 

_No response_

**Comment by Zahyra16** [comment]
Esta pagina cambia de dirección a muy menudo debido al Copyright, pero no modifica nada de su interfaz, no seria mejor crear una extensión en la cual se cambie solo su URL en los ajustes de la extensión, varias apps de contenido multimedia o lectura de novelas que también funcionan con extensiones, tienen una función para clonar sitios web idénticos, solo digo mi humilde opinión de alguien que no sabe programación. 🙂
________________________________
This page changes its web address very often due to copyright, but it doesn't change anything of its interface, wouldn't it be better to create an extension in which only its URL is changed in the extension settings, several apps for multimedia content or reading novels that also work with extensions, have a function to clone identical websites, I just say my humble opinion of someone who doesn't know programming 🙂

**Comment by matheuswr89** [comment]
@Zahyra16 I think that something similar to what is done in the Ikai Mangas extension is possible to do for Olympus, I will analyze and implement this.
